---
title: "COPLAS_ts"
output: html_document
---

```{r}
# Definir directorio: si se abre desde "Project" es necesario abrirlo desde el menú (Session>Set working directory>...)
setwd("C:/DELL/GDrive_2/Instar/calibracion_validacion/fuentes_datos_validacion/COPLAS_PLAGAS/")
```

# Analisis de COPLAS como serie temporal

```{r}
COPLAS<-read.csv("Grados_procesionaria_completo_junio_2016.csv", header=TRUE, dec =".", sep=";")
names(COPLAS)[3] <- "CAMPANA"
```

Codigo rodal: GR-XXX-XXX (GR-Granada, AL-Almeria,...).

Rodales de SN: 29, 67, 69, 70, 71, 73, 75, 94001, 94005, 94006, 94007, 94010, 134003, 134004, 134005, 134006, 134007, 134013, 134014, 134015 (los digitos que faltan son 0)

Rodales de SB: 6, 7, 8, 9, 10, 12, 13, 15, 17, 21 (no están todos; los digitos que faltan son 0)

```{r}
rodal_X <- subset(COPLAS, COPLAS$RODAL == "GR-000-007") # seleccion de un rodal
```

```{r}
start_year <- min(rodal_X$CAMPANA)
end_year <- max(rodal_X$CAMPANA)

ts_rod_X <- ts(rodal_X$GRADO.REVISADO, start=start_year, end = end_year, frequency = 1) # Definimos los datos como serie temporal

plot(ts_rod_X, xlim= c(1993,2015), ylim = c(0,5), ylab = "COPLAS", xlab="Time") # visualizacion
```